/* eslint-disable linebreak-style,camelcase */
import I18n from 'ex-react-native-i18n';

I18n.fallbacks = true;

I18n.translations = {
  // ENGLISH
  en:{
    general:{
      reminder: 'Reminder',
      regulation_acceptance_statement: 'I hereby accept the regulation of Gymgang',
      regulation_place: 'You can find regulation on'
    },
    clubs:{
      clubs:'Clubs',
      club:'Club',
      my_clubs:'My Clubs',
      search_clubs:'Search Clubs',
      name:'Name',
      locale:'Location',
      schedule: 'Opening hours',
      address:'Address',
      street:'Street',
      city:'City',
      phone:'Phone',
      add_to_my_clubs:'Add To My Clubs',
      delete_from_my_clubs:'Delete From My Clubs',
      raiting: 'Go to raiting',
      rate: 'Rating',
      check_in: 'Check in',
      no_more_clubs: 'Select no more than 5 clubs'
    },
    week: {
      sunday: 'sunday',
      monday: 'monday',
      tuesday: 'tuesday',
      wednesday: 'wednesday',
      thursday: 'thursday',
      friday: 'friday',
      saturday: 'saturday'
    },
    notifications:{
      notifications:'Notifications'
    },
    user_card:{
      train_together:'Train Together',
      chat:'Chat',
      clubs:'Clubs',
      disciplines:'Disciplines',
      city:'City',
      no_selected_clubs:'No selected clubs',
      friends: 'Friends',
      favourite: 'Favourite',
      tab_friends: 'Mutual friends',
      tab_clubs: 'Mutual clubs',
      achievements: 'Achievements',
      challenges: 'Challenges'
    },
    train_together:{
      train_together:'Train Together',
      next:'Next',
      suggested_by:'Suggested by',
      club:'Club',
      yes:'Yes',
      no:'No',
      location:'Location',
      suggested_workouters: 'Sugerowani trenujący'
    },
    friends:{
      friends:'Friends',
      my_friends:'My Friends',
      suggested_friends:'Suggested Friends',
      chat: 'Chat with friends',
      find_friends:'Find Friends',
      add_to_friends:'Add To Friends',
      delete_from_my_friends:'Remove From My Friends'
    },
    muscle_parts:{
      traps:'Traps',
      shoulders:'Shoulders',
      chest:'Chest',
      biceps:'Biceps',
      triceps:'Triceps',
      forearm:'Forearm',
      abs:'Abs',
      middleBack:'Middle Back',
      lowBack:'Lower Back',
      glutes:'Glutes',
      quads:'Quads',
      hamstrings:'Hamstrings',
      calves:'Calves'
    },
    body_parts:{
      body_parts:'Body Parts',
      chest:'Chest',
      biceps:'Biceps',
      forearm:'Forearm',
      waist:'Waist',
      belt:'Belt',
      hips:'Hips',
      thigh:'Thigh',
      calf:'Calf',
      weight:'Weight'
    },
    drawer:{
      account:'Account',
      shop:'Take your discount',
      settings:'Settings',
      dashboard:'Dashboard',
      train_together:'Train Together',
      workout_notes:'Workout Notes',
      edit_profile:'Edit Profile',
      clubs:'Clubs',
      friends:'Friends',
      disciplines:'Edit Disciplines',
      logout:'Logout'
    },
    login:{
      password:'Password',
      dont_have_an_account:`Don't have an account?`,
      log_in_to_your_social_media_account:'Log in to your social media account'
    },
    register:{
      password:'Password',
      username:'Username',
      email:'Email',
      confirmPassword:'Confirm Password',
      already_have_an_account:'Already have an account?'
    },
    dashboard:{
      train_together:'Train Together',
      workout_notes:'Workout Notes',
      sport_clubs:'Sport Clubs',
      friends:'Friends'
    },
    edit_profile:{
      your_profile:'Your Profile',
      name:'First name / Last name',
      birthday:'Birthday',
      gender:'Gender',
      male:'Male',
      female:'Female',
      name_missing: 'Please fill your username',
      birthday_missing: 'Please choose your birthdate',
      warning: 'Warning'
    },
    disciplines:{
      disciplines:'Your Disciplines',
      gym:'Gym',
      basketball:'Basketball',
      football:'Football',
      cross_fit:'Cross-fit',
      jogging:'Jogging',
      cycling:'Cycling',
      tennis:'Tennis',
      squash:'Squash',
      badminton:'Badminton',
      soccer:'Soccer',
      baseball:'Baseball',
      hockey:'Hockey',
      golf:'Golf'
    },
    workout_notes:{
      workout_notes:'Workout notes',
      create_new_training:'Create new training',
      use_of_existing_training:'Use of existing training',
      calendar_of_training:'Calendar of training',
      statistics:'Statistics',
      cross_fit_training:'Cross Fit training',
      body_measurements:'Body measurement'
    },
    create_training:{
      create_training:'Create Training',
      add_muscle_exercise:'Add Muscle Training',
      add_cardio_exercise:'Add Cardio Exercise',
      functional_exercises:'Functional Exercises',
      list_of_selected_exercises:'Selected Exercises',
      list_of_favourite_exercises:'Favourite Exercises',
      save_training:'Save Training'
    },
    exercises:{
      add_to_favourites: 'Add to favourites',
      favourite: 'My favourite',
      add_exercise: 'Add custom exercise',
      add_exercise_name: 'Add exercise name'
    },
    muscle_exercises:{
      muscle_exercises:'Add Muscle Exercises',
      muscle_part:'Muscle Part'
    },
    cardio_exercise:{
      cardio_exercise:'Add Cardio Exercises',
      bike:'Bike',
      track:'Track',
      stairs:'Stairs',
      elliptical: 'Elliptical',
      intervals: 'Intervals',
      rower: 'Rower'
    },
    define_functional:{
      define_functional:'Define Functional Exercise',
      reps_count:'Repeats Count',
      time_count:'Time (s)'
    },
    define_muscle:{
      define_muscle:'Define Muscle Exercise',
      series_count:'Series Count',
      reps_count:'Repeats Count',
      weight_count:'Weight (kg)'
    },
    alerts:{
      blank_training:'Training may not be blank!'
    },
    define_cardio:{
      define_cardio:'Define Cardio Exercise',
      length:'Length',
      time:'Time',
      level:'Level',
      warmUp:'WarmUp',
      fastPace:'Fast Pace',
      slowPace:'Slow Pace',
      repeats:'Repeats'
    },
    calendar_of_training:{
      calendar_of_training:'Training Calendar',
      training_name:'Training Name'
    },
    body_measurements:{
      body_measurements:'Body Measurements',
      chest:'Chest',
      biceps:'Biceps',
      forearm:'Forearm',
      waist:'Waist',
      belt:'Belt',
      hips:'Hips',
      thigh:'Thigh',
      calf:'Calf',
      weight:'Weight',
      traps:'Traps',
      shoulders:'Shoulders',
      triceps:'Triceps',
      abs:'Abs',
      lats:'Lats',
      middle_back:'Middle Back',
      lower_back:'Lower Back',
      glutes:'Glutes',
      quads:'Quads',
      hamstrings:'Hamstrings',
      calves:'Calves',
      date_measurement:'Date of measurement',
      reminder: 'You didn\'t submit your body measurement today.'
    },
    statistics:{
      statistics:'Statistics',
      selected_exercises:'Selected Exercises',
      exercise_statistics:'Exercise Statistics',
      cardio_statistics:'Cardio Statistics',
      cross_fit_statistics:'Cross Fit Statistics',
      body_measurement_statistics:'Body measurement Statistics',
      body_part_statistics:'Body Part Stats',
      chosen_body_part:'Chosen Body Part',
      chosen_exercise:'Chosen Exercise',
      choose_exercise:'Choose Exercise',
      weight:'Weight',
      reps:'Reps',
      centimeters:'Cm',
      days:'Day'
    },
    existing_trainings:{
      existing_trainings:'Existing Trainings',
      edit_training: 'Edit exercises',
      remove_training: 'Remove training',
      training_removal: 'Remove training',
      removal_confirmation: 'Are you sure want to remove this training?'
    },
    buttons:{
      save:'Save',
      login:'Log in',
      signin:'Sign in',
      close:'Close',
      cancel:'Cancel',
      delete: 'Delete',
      remove: 'Remove',
    },
    shop:{
      click_on_ad: 'Tap on ad to get into shop.',
      place_for_ad: 'Place for your ad'
    },
    muscle_exercises_names:{
      // abs:{
      bicycle_kicks:'bicycle kicks',
      Bent_Legs_Cross_Crunches:'Bent Legs Cross Crunches',
      Raised_Legs_Cross_Crunches:'Raised Legs Cross Crunches',
      Bent_Legs_Crunches:'Bent Legs Crunches',
      Raised_Legs_Crunches:'Raised Legs Crunches',
      Decline_Bench_Crunches:'Decline Bench Crunches',
      dotykanie_piet_lezac:'dotykanie piet lezac',
      nozyce_lezac:'nozyce lezac',
      odwodzenie_kolana_w_tyl_w_podparciu_przodem:'odwodzenie kolana w tyl w podparciu przodem',
      odwodzenie_nogi_w_tyl_w_podparciu_przodem:'odwodzenie nogi w tyl w podparciu przodem',
      odwrotne_spiecia_brzucha_uniesione_nogi:'odwrotne spiecia brzucha uniesione nogi',
      plank:'plank',
      przyciaganie_nog_do_klatki_piersiowej_lezac:'przyciaganie nog do klatki piersiowej lezac',
      rowerek_spiecia_brzucha:'rowerek spiecia brzucha',
      rowerek_spiecia_brzucha_ze_skretem_tulowia:'rowerek spiecia brzucha ze skretem tulowia',
      scyzoryki_lezac_v_ups:'scyzoryki lezac v ups',
      skrety_tulowia_ze_sztanga_stojac:'skrety tulowia ze sztanga stojac',
      sklony_boczne_na_lawce_rzymskiej:'sklony boczne na lawce rzymskiej',
      sklony_boczne_z_linka_wyciagu_stojac:'sklony boczne z linka wyciagu stojac',
      Sklony_boczne_z_hantlami_stojac:'Sklony boczne z hantlami stojac',
      spiecia_brzucha_laweczka_ujemna:'spiecia brzucha laweczka ujemna',
      spiecia_brzucha_bokiem_na_maszynie_siedzac:'spiecia brzucha bokiem na maszynie siedzac',
      spiecia_brzucha_lezac_bokiem:'spiecia brzucha lezac bokiem',
      spiecia_brzucha_na_maszynie_siedzac:'spiecia brzucha na maszynie siedzac',
      spiecia_brzucha_na_wyciagu_stojac:'spiecia brzucha na wyciagu stojac',
      spiecia_brzucha_z_podpaciem_nog_lezac:'spiecia brzucha z podpaciem nog lezac',
      spiecia_brzucha_z_podparciem_nog_lezac_bokiem:'spiecia brzucha z podparciem nog lezac bokiem',
      spiecia_brzucha_ugiete_nogi:'spiecia brzucha ugiete nogi',
      spiecia_brzucha_uniesione_nogi:'spiecia brzucha uniesione nogi',
      toczenie_sztangi_kleczac:'toczenie sztangi kleczac',
      unoszenie_bioder_nogi_w_gorze_lezac:'unoszenie bioder nogi w gorze lezac',
      unoszenie_bioder_ugiete_nogi_lezac:'unoszenie bioder ugiete nogi lezac',
      unoszenie_kolan_w_zwisie:'unoszenie kolan w zwisie',
      unoszenie_nog_lezac:'unoszenie nog lezac',
      unoszenie_nog_w_zwisie:'unoszenie nog w zwisie',
      unoszenie_tulowia_z_nogami_w_gorze_lezac:'unoszenie tulowia z nogami w gorze lezac',
      sciaganie_linki_wyciagu_gornego_prz_prostych_lokciach_stojac:'sciaganie linki wyciagu gornego prz prostych lokciach stojac',
      // },
      // biceps:{
      incline_hammer_curls:'incline hammer curls',
      incline_inner_biceps_curl:'incline inner biceps curl',
      standing_concentration_curl:'standing concentration curl',
      ez_bar_curl:'ez bar curl',
      wide_grip_standing_barbell_curl:'wide grip standing barbell curl',
      zottman_curl:'zottman curl',
      barbell_curl:'barbell curl',
      dumbbell_biceps_curl:'dumbbell biceps curl',
      hammer_curl:'hammer curl',
      overhead_cable_curl:'overhead cable curl',
      Seated_Alternate_Reverse_Grip_Dumbbell_Curls:'Seated Alternate Reverse Grip Dumbbell Curls',
      Standing_Alternate_Reverse_Grip_Dumbbell_Curls:'Standing Alternate Reverse Grip Dumbbell Curls',
      Alternate_Dumbbell_Hammer_Curls:'Alternate Dumbbell Hammer Curls',
      Medium_Overhand_Grip_Pull_up:'Medium Overhand Grip Pull-up',
      Assisting_Machine_Medium_Overhand_Grip_Pull_up:'Assisting Machine Medium Overhand Grip Pull-up',
      Medium_Underhand_Grip_Pull_up:'Medium Underhand Grip Pull-up',
      Assisting_Machine_Medium_Underhand_Grip_Pull_up:'Assisting Machine Medium Underhand Grip Pull-up',
      Close_Overhand_Grip_Pull_up:'Close Overhand Grip Pull-up',
      Single_arm_Dumbbell_Curl:'Single-arm Dumbbell Curl',
      Cross_Body_Cable_Curls:'Cross Body Cable Curls',
      Standing_Cross_Body_Dumbbell_Curls:'Standing Cross Body Dumbbell Curls',
      Seated_Cross_Body_Dumbbell_Curls:'Seated Cross Body Dumbbell Curls',
      Seated_Machine_Reverse_Grip_Curls:'Seated Machine Reverse Grip Curls',
      Scotts_Machine_Preacher_Curls:`Scott's Machine Preacher Curls`,
      Standing_Over_Head_Cable_Curls:'Standing Over Head Cable Curls',
      Lying_Cable_Curls:'Lying Cable Curls',
      Standing_Cable_Curls:'Standing Cable Curls',
      Preacher_Cable_Curls:'Preacher Cable Curls',
      Incline_Bench_Cable_Curls:'Incline Bench Cable Curls',
      Bench_Cable_Curls:'Bench Cable Curls',
      Standing_Hammer_Curl:'Standing Hammer Curl',
      Dumbbel_Preacher_Curl:'Dumbbel Preacher Curl',
      Dumbbell_Prone_Incline_Curl:'Dumbbell Prone Incline Curl',
      Incline_Seated_Dumbbell_Curl:'Incline Seated Dumbbell Curl',
      Seated_Reverse_Grip_Curls:'Seated Reverse Grip Curls',
      Standing_Reverse_Dumbbell_Curl:'Standing Reverse Dumbbell Curl',
      Standing_Wide_Grip_EZ_Barbell_Curls:'Standing Wide Grip EZ Barbell Curls',
      Preacher_Barbell_Curl:'Preacher Barbell Curl',
      Barbell_Prone_Incline_Curls:'Barbell Prone Incline Curls',
      Incline_Seated_Barbell_Curl:'Incline Seated Barbell Curl',
      Standing_Barbell_Curl:'Standing Barbell Curl',
      EZ_Bar_Preacher_Curl:'EZ Bar Preacher Curl',
      Standing_Reverse_Grip_EZ_Bar_Curls:'Standing Reverse Grip EZ Bar Curls',
      Standing_Close_Grip_EZ_Bar_Curls:'Standing Close Grip EZ Bar Curls',
      Standing_Wide_Grip_EZ_Bar_Curls:'Standing Wide Grip EZ Bar Curls',
      Standing_Close_Grip_Barbell_Curls:'Standing Close Grip Barbell Curls',
      Standing_Upright_Dumbbell_Row:'Standing Upright Dumbbell Row',
      Standing_Upright_Barbell_Row:'Standing Upright Barbell Row',
      Standing_Upright_Cable_Row:'Standing Upright Cable Row',
      Standing_Upright_Smith_Machine_Barbell_Row:'Standing Upright Smith Machine Barbell Row',
      sciaganie_drazka_wyciagu_gornego_do_klatki_piersiowej_nadchwytem_waski:'sciaganie drazka wyciagu gornego do klatki piersiowej nadchwytem waski',
      sciaganie_drazka_wyciągu_gornego_do_klatki_piersiowej_podchwytem_waski:'sciaganie drazka wyciągu gornego do klatki piersiowej podchwytem waski',
      // },
      // chest:{
      Barbell_bench_press:'Barbell bench press',
      Flat_bench_dumbbell_press:'Flat bench dumbbell press',
      Low_incline_barbell_bench_press:'Low incline barbell bench press',
      Machine_decline_press:'Machine decline press',
      Seated_machine_chest_press:'Seated machine chest press',
      Incline_dumbbell_press:'Incline dumbbell press',
      Dips_for_chest:'Dips for chest',
      Incline_bench_cable_fly:'Incline bench cable fly',
      Incline_dumbbell_pull_over:'Incline dumbbell pull over',
      Pec_deck_machine:'Pec deck machine',
      Standing_Cable_Crossovers:'Standing Cable Crossovers',
      Assisting_Machine_Dips:'Assisting Machine Dips',
      Wide_Grip_Bent_Over_Dips:'Wide Grip Bent Over Dips',
      Handrail_Bent_Over_Dips:'Handrail Bent Over Dips',
      Wide_Grip_Push_ups_with_Leg_on_Suspension:'Wide Grip Push-ups with Leg on Suspension',
      Wide_Grip_Push_ups:'Wide Grip Push-ups',
      Cable_Crossovers:'Cable Crossovers',
      Przenoszenie_sztangi_za_głowę:'Przenoszenie sztangi za głowę',
      Przenoszenie_sztangi_łamanej_za_głowę:'Przenoszenie sztangi łamanej za głowę',
      Przenoszenie_hantli_za_głowę:'Przenoszenie hantli za głowę',
      Flys:'Flys',
      Incline_Bench_Cable_Flys:'Incline Bench Cable Flys',
      Pec_Dec_Seated_Machine_Flys:'Pec Dec, Seated Machine Flys',
      Decline_Bench_Cable_Flys:'Decline Bench Cable Flys',
      Incline_Dumbbell_Flys:'Incline Dumbbell Flys',
      Dumbbell_Flys:'Dumbbell Flys',
      Decline_Dumbbell_Flys:'Decline Dumbbell Flys',
      Incline_Dumbbell_Flys_with_Supination:'Incline Dumbbell Flys with Supination',
      Dumbbell_Flys_with_Supination:'Dumbbell Flys with Supination',
      Decline_Dumbbell_Flys_with_Supination:'Decline Dumbbell Flys with Supination',
      Front_Seated_Machine_Press:'Front Seated Machine Press',
      Incline_Machine_Press:'Incline Machine Press',
      Machine_Press:'Machine Press',
      Decline_Machine_Press:'Decline Machine Press',
      Wide_Grip_Incline_Smith_Machine_Bench_Press:'Wide Grip Incline Smith Machine Bench Press',
      Wide_Grip_Smith_Machine_Bench_Press:'Wide Grip Smith Machine Bench Press',
      Wide_Grip_Decline_Smith_Machine_Bench_Press:'Wide Grip Decline Smith Machine Bench Press',
      Incline_Smith_Machine_Bench_Press:'Incline Smith Machine Bench Press',
      Smith_Machine_Bench_Press:'Smith Machine Bench Press',
      Decline_Smith_Machine_Bench_Press:'Decline Smith Machine Bench Press',
      Wide_Grip_Incline_Barbell_Bench_Press:'Wide Grip Incline Barbell Bench Press',
      Decline_Barbell_Bench_Press:'Decline Barbell Bench Press',
      Wide_Grip_Decline_Barbell_Bench_Press:'Wide Grip Decline Barbell Bench Press',
      Palms_in_Incline_Dumbbell_Bench_Press:'Palms in Incline Dumbbell Bench Press',
      Palms_in_Dumbbell_Bench_Press:'Palms in Dumbbell Bench Press',
      Palms_in_Decline_Dumbbell_Bench_Press:'Palms in Decline Dumbbell Bench Press',
      Incline_Seated_Dumbell_Press:'Incline Seated Dumbell Press',
      Dumbbell_Bench_Press:'Dumbbell Bench Press',
      Decline_Dumbbel_Bench_Press:'Decline Dumbbel Bench Press',
      // },
      // calves:{
      Standing_machine_calf_raises:'Standing machine calf raises',
      Smith_machine_calf_raises:'Smith machine calf raises',
      One_legged_dumbbell_calf_raises:'One legged dumbbell calf raises',
      Leg_press_calf_raise:'Leg press calf raise',
      Seated_machine_calf_raises:'Seated machine calf raises',
      Wspięcia_na_palce_ze_sztangą_siedząc:'Wspięcia na palce ze sztangą siedząc',
      Wspięcia_na_palce_ze_sztangą_stojąc:'Wspięcia na palce ze sztangą stojąc',
      // },
      // forearm:{
      Barbell_wrist_curls:'Barbell wrist curls',
      Barbell_reverse_wrist_curls:'Barbell reverse wrist curls',
      Dumbbell_wrist_curl:'Dumbbell wrist curl',
      Dumbbell_reverse_wrist_curl:'Dumbbell reverse wrist curl',
      Reverse_barbell_curls:'Reverse barbell curls',
      Standing_Wrist_Cable_Reverse_Curls:'Standing Wrist Cable Reverse Curls',
      Standing_Reverse_Wrist_Curls_with_Barbell_Plate:'Standing Reverse Wrist Curls with Barbell Plate',
      Standing_Barbell_Reverse_Wrist_Curls:'Standing Barbell Reverse Wrist Curls',
      Close_Overhand_Grip_Pull_up:'Close Overhand Grip Pull-up',
      Seated_Lateral_Wrist_Cable_Curls:'Seated Lateral Wrist Cable Curls',
      Standing_Wrist_Cable_Curls:'Standing Wrist Cable Curls',
      Seated_Underhand_Dumbbell_Wrist_Curls:'Seated Underhand Dumbbell Wrist Curls',
      Seated_Underhand_Barbell_Wirst_Curls:'Seated Underhand Barbell Wrist Curls',
      Standing_Underhand_Barbell_Wrist_Curls:'Standing Underhand Barbell Wrist Curls',
      Standing_Underhand_Behind_Barbell_Wirst_Curls:'Standing Underhand Behind Barbell Wrist Curls',
      Seated_Underhand_EZ_Bar_Wrist_Curls:'Seated Underhand EZ Bar Wrist Curls',
      // },
      // glutes:{
      squats:'squats',
      Weighted_Walking_Lunges:'Weighted Walking Lunges',
      Barbell_Hip_Thrusts:'Barbell Hip Thrusts',
      Stiff_Legged_Deadlifts:'Stiff Legged Deadlifts',
      Bulgarian_Split_Squats:'Bulgarian Split Squats',
      Wide_Stand_Barbell_Sumo_Deadlift:'Wide Stand Barbell Sumo Deadlift',
      Dumbbell_Deadlift:'Dumbbell Deadlift',
      Barbell_Deadlift:'Barbell Deadlift',
      Cable_Deadlift:'Cable Deadlift',
      Nożyce_leżąc:'Nożyce leżąc',
      odwodzenie_nogi_w_tył_klęcząc:'odwodzenie nogi w tył klęcząc',
      Odwodzenie_nogi_w_tył_na_maszynie:'Odwodzenie nogi w tył na maszynie',
      Odwodzenie_nogi_w_tył_ze_zgięciem_kolana_klęcząc:'Odwodzenie nogi w tył ze zgięciem kolana klęcząc',
      Odwodzenie_nogi_z_linką_wyciągu_stojąc:'Odwodzenie nogi z linką wyciągu stojąc',
      Odwodzenie_nóg_na_maszynie_siedząc:'Odwodzenie nóg na maszynie siedząc',
      Przeciąganie_linki_wyciągu_stojąc:'Przeciąganie linki wyciągu stojąc',
      Laverage_Machine_Standing_Squats:'Laverage Machine Standing Squats',
      Incline_Bench_Machine_Squats:'Incline Bench Machine Squats',
      Smith_Machine_Standing_Front_Squats:'Smith Machine Standing Front Squats',
      Kneeling_Barbell_Squats:'Kneeling Barbell Squats',
      Deep_Squat:'Deep Squat',
      Standing_Neck_Barbell_Squats:'Standing Neck Barbell Squats',
      Back_Squats:'Back Squats',
      Seated_Machine_Legs_Adduction:'Seated Machine Legs Adduction',
      Standing_Barbell_Back_Curls:'Standing Barbell Back Curls',
      Unoszenie_bioder_ugięte_nogi_leżąc:'Unoszenie bioder ugięte nogi leżąc',
      Weighted_Walking_Lunges:'Weighted Walking Lunges',
      Lunges_with_Barbell:'Lunges with Barbell',
      Incline_Press_Machine_Leg_Press:'Incline Press Machine Leg Press',
      // },
      // hamstrings:{
      clean_deadlift:'clean deadlift',
      romanian_deadlift_from_deficit:'romanian deadlift from deficit',
      kettlebell_one_legged_deadlift:'kettlebell one legged deadlift',
      power_snatch:'power snatch',
      hang_snatch:'hang snatch',
      floor_glute_ham_raise:'floor glute ham raise',
      power_clean_from_blocks:'power clean from blocks',
      lying_leg_curls:'lying leg curls',
      sumo_deadlift:'sumo deadlift',
      Standing_Cable_Leg_Curls:'Standing Cable Leg Curls',
      Front_Lying_Machine_Legs_Curls:'Front Lying Machine Legs Curls',
      Seated_Machine_Legs_Curls:'Seated Machine Legs Curls',
      Standing_Machine_Legs_Curls:'Standing Machine Legs Curls',
      // },
      // lats:{
      Leverage_iso_row:'Leverage iso row',
      Wide_grip_lat_pull_down:'Wide grip lat pull down',
      Underhand_cable_pull_down:'Underhand cable pull down',
      Straight_arm_pull_down:'Straight arm pull down',
      V_bar_pull_down:'V bar pull down',
      Close_grip_front_lat_pull_down:'Close grip front lat pull down',
      V_bar_pull_up:'V bar pull up',
      Rocky_pull_up:'Rocky pull up',
      Chin_up:'Chin up',
      // },
      // lowBack:{
      Wide_Stand_Barbell_Sumo_Deadlift:'Wide Stand Barbell Sumo Deadlift',
      Dumbbell_Deadlift:'Dumbbell Deadlift',
      Barbell_Deadlift:'Barbell Deadlift',
      Cable_Deadlift:'Cable Deadlift',
      Prostowanie_grzbietu_na_maszynie:'Prostowanie grzbietu na maszynie',
      Prostowanie_grzbietu_na_maszynie_siedząc:'Prostowanie grzbietu na maszynie siedząc',
      Prostowanie_grzbietu_na_ławce_poziomej_leżąc_przodem:'Prostowanie grzbietu na ławce poziomej leżąc przodem',
      Przeciąganie_linki_wyciągu_stojąc:'Przeciąganie linki wyciągu stojąc',
      Laverage_Machine_Standing_Squats:'Laverage Machine Standing Squats',
      Kneeling_Barbell_Squats:'Kneeling Barbell Squats',
      Standing_Deep_Squat:'Standing Deep Squat',
      Standing_Neck_Barbell_Squats:'Standing Neck Barbell Squats',
      Front_Lying_Back_Curls:'Front Lying Back Curls',
      Seated_Barbell_Back_Curls:'Seated Barbell Back Curls',
      Standing_Barbell_Back_Curls:'Standing Barbell Back Curls',
      // },
      // middleBack:{
      Barbell_deadlift:'Barbell deadlift',
      Bent_over_barbell_deadlift:'Bent over barbell deadlift',
      Wide_grip_pull_up:'Wide grip pull up',
      Standing_t_bar_row:'Standing t bar row',
      Wide_grip_seated_cable_row:'Wide grip seated cable row',
      Reverse_grip_smith_machine_row:'Reverse grip smith machine row',
      Close_grip_pull_down:'Close grip pull down',
      Single_arm_dumbbell_row:'Single arm dumbbell row',
      Decline_bench_dumbbell_pull_over:'Decline bench dumbbell pull over',
      Single_arm_smith_machine_row:'Single arm smith machine row',
      Medium_Overhand_Grip_Pull_up:'Medium Overhand Grip Pull up',
      Assisting_Machine_Wide_Overhand_Grip_Pull_up:'Assisting Machine Wide Overhand Grip Pull up',
      Assisting_Machine_Medium_Overhand_Grip_Pull_up:'Assisting Machine Medium Overhand Grip Pull up',
      Wide_Underhand_Grip_Pull_up:'Wide Underhand Grip Pull up',
      Medium_Underhand_Grip_Pull_up:'Medium Underhand Grip Pull up',
      Assisting_Machine_Close_Underhand_Grip_Pull_up:'Assisting Machine Close Underhand Grip Pull-up',
      Assisting_Machine_Medium_Underhand_Grip_Pull_up:'Assisting Machine Medium Underhand Grip Pull-up',
      Assisting_Machine_Wide_Underhand_Grip_Pull_up:'Assisting Machine Medium Underhand Grip Pull-up',
      Wide_Overhand_Grip_Pull_up:'Wide Overhand Grip Pull up',
      Tipup_ze_sztangą_w_opadzie_stojąc:'Tipup ze sztangą w opadzie stojąc',
      Leverage_Machine_Seated_Row:'Leverage Machine Seated Row',
      Seated_Cable_Row:'Seated Cable Row',
      Decline_Seated_Cable_Row:' Decline Seated Cable Row',
      Bench_Dumbbell_Row_Front_Lying:'Bench Dumbbell Row Front Lying',
      Bent_Over_Dumbbell_Row:'Bent Over Dumbbell Row',
      Smith_Machine_Standing_Bent_Over_Row:'Smith Machine Standing Bent Over Row',
      Bench_Barbell_Row_Front_Lying:'Bench Barbell Row Front Lying',
      Reverse_Grip_Bent_Over_Barbell_Rows:'Reverse Grip Bent Over Barbell Rows',
      Bent_Over_Barbell_Row:'Bent Over Barbell Row',
      Ściąganie_droążka_wyciągu_górnego_do_karku_szeroki_rozstaw_rąk_siedząc:'Ściąganie drążka wyciągu górnego do karku szeroki rozstaw rąk siedząc',
      Ściąganie_drażka_wyciągu_górnego_do_klatki_piersiowej_nadchwytem_wąski_rozstaw_rąk:'Ściąganie drażka wyciągu górnego do klatki piersiowej nadchwytem wąski rozstaw rąk',
      Ściąganie_drążka_wyciągu_górnego_do_klatki_piersiowej_podchwytem_wąski_rozstaw_rąk:'Ściąganie drążka wyciągu górnego do klatki piersiowej podchwytem wąski rozstaw rąk',
      Ściąganie_drążka_wyciągu_górnego_do_klatki_piersiowej_szeroki_rozstaw_rąk:'Ściąganie drążka wyciągu górnego do klatki piersiowej szeroki rozstaw rąk',
      Ściąganie_na_maszynie_leverage_siedząc:'Ściąganie na maszynie leverage siedząc',
      // },
      // quads:{
      Box_squat_with_bands:'Box squat with bands',
      Barbell_lunge:'Barbell lunge',
      Narrow_stance_squats:'Narrow stance squats',
      Goblet_squat:'Goblet squat',
      Frankenstein_squat:'Frankenstein squat',
      Box_squat:'Box squat',
      Kettlebell_pistol_squat:'Kettlebell pistol squat',
      Front_squat_clean_grip:'Front squat clean grip',
      Barbell_squat:'Barbell squat',
      Front_squats_with_two_kettlebells:'Front squats with two kettlebells',
      Dynamiczne_podskoki:'Dynamiczne podskoki',
      Dumbbell_Deadlift:'Dumbbell Deadlift',
      Barbell_Deadlift:'Barbell Deadlift',
      Cable_Deadlift:'Cable Deadlift',
      Odwodzenie_nóg_na_maszynie_siedząc:'Odwodzenie nóg na maszynie siedząc',
      Odwodznie_nóg_na_maszynie_stojąc:'Odwodznie nóg na maszynie stojąc',
      Prostowanie_nóg_na_maszynie_siedząc:'Prostowanie nóg na maszynie siedząc',
      Laverage_Machine_Standing_Squats:'Laverage Machine Standing Squats',
      Incline_Bench_Machine_Squats:'Incline Bench Machine Squats',
      Smith_Machine_Standing_Front_Squats:'Smith Machine Standing Front Squats',
      Smith_Machine_Standing_Back_Squats:'Smith Machine Standing Back Squats',
      Deep_Squat:'Deep Squat',
      Standing_Neck_Barbell_Squats:'Standing Neck Barbell Squats',
      Back_Squats:'Back Squats',
      Seated_Machine_Legs_Adduction:'Seated Machine Legs Adduction',
      Standing_Machine_Legs_Adduction:'Standing Machine Legs Adduction',
      Step_with_Dumbbells:'Step with Dumbbells',
      Step_with_Barbell:'Step with Barbell',
      Lunges_with_Barbell:'Lunges with Barbell',
      Lunges_with_Bag:'Lunges with Bag',
      Lunges_with_Dumbbells:'Lunges with Dumbbells',
      Incline_Press_Machine_Leg_Press:'Incline Press Machine Leg Press',
      // },
      // shoulders:{
      Cable_reverse_flye:'Cable reverse flye',
      Bent_over_dumbbell_lateral_raise:'Bent over dumbbell lateral raise',
      One_arm_cable_lateral_raise:'One arm cable lateral raise',
      Cable_front_raise:'Cable front raise',
      Push_press:'Push press',
      Wide_grip_smith_machine_upright_row:'Wide grip smith machine upright row',
      Face_pull:'Face pull',
      Dumbbell_lateral_raise:'Dumbbell lateral raise',
      Seated_barbell_shoulder_press:'Seated barbell shoulder press:',
      Seated_dumbbell_shoulder_press:'Seated dumbbell shoulder press',
      Machine_Reverse_Dumbbell_Flys:'Machine Reverse Dumbbell Flys',
      Seated_Machine_Reverse_Dumbbell_Flys:'Seated Machine Reverse Dumbbell Flys',
      Front_Reverse_Dumbbell_Flys:'Front Reverse Dumbbell Flys',
      Hand_stand_Push_ups:'Hand-stand Push-ups',
      Standing_Single_arm_Front_Cable_Raise:'Standing Single-arm Front Cable Raise',
      Leaning_Dumbbel_Lateral_Raise:'Leaning Dumbbel Lateral Raise',
      Standing_Front_Cable_Raise:'Standing Front Cable Raise',
      Standing_Barbell_Plate_Front_Raise:'Standing Barbell Plate Front Raise',
      Standing_Dumbbell_Front_Raise:'Standing Dumbbell Front Raise',
      Standing_Barbell_Front_Raise:'Standing Barbell Front Raise',
      Cable_Lateral_Raise:'Cable Lateral Raise',
      Standing_Upright_Barbell_Row:'Standing Upright Barbell Row',
      Standing_Upright_Cable_Row:'Standing Upright Cable Row',
      Standing_Upright_Smith_Machine_Barbell_Row:'Standing Upright Smith Machine Barbell Row',
      Wyciskanie_sprzed_głowy_na_maszynie_siedząc:'Back Seated Machine Press',
      Wyciskanie_sprzed_głowy_na_suwnicy_Smitha_siedząc:'Smith Machine Bench Press Seated',
      Standing_Back_Barbell_Press:'Standing Back Barbell Press',
      Standing_Barbell_Press_Behind_Neck:'Standing Barbell Press Behind Neck',
      Incline_Seated_Dumbell_Press:'Incline Seated Dumbell Press',
      Seated_Dumbell_Press:'Seated Dumbell Press',
      // },
      // traps:{
      Barbell_shrug:'Barbell shrug',
      Barbell_shrug_behind_the_back:'Barbell shrug behind the back',
      Cable_shrugs:'Cable shrugs',
      Calf_machine_shoulder_shrug:'Calf machine shoulder shrug',
      Clean_shrug:'Clean shrug',
      Dumbbell_shrug:'Dumbbell shrug',
      Kettlebell_sumo_high_pull:'Kettlebell sumo high pull',
      Leverage_shrug:'Leverage shrug',
      Scapular_pull_up:'Scapular pull up',
      Smith_machine_behind_the_back_shrug:'Smith machine behind the back shrug',
      Smith_machine_shrug:'Smith machine shrug',
      Smith_machine_upright_row:'Smith machine upright row',
      Snatch_shrug:'Snatch shrug',
      Standing_dumbbell_upright_row:'Standing dumbbell upright row',
      Upright_cable_row:'Upright cable row',
      Upright_row_with_bands:'Upright row with bands',
      // },
      // triceps: {
      Dumbbell_rollbacks:'Dumbbell rollbacks',
      Board_close_grip_bench_press:'Board close grip bench press',
      Kickbacks_with_a_twist:'Kickbacks with a twist',
      Rep_hold_push_downs:'Rep hold push downs',
      Clos_Grip_Decline_Barbell_Bench_Press:'Close Grip Decline Barbell Bench Press',
      Odwodzenie_przedramion_z_linkami_wyciągu_w_opadzie:'Odwodzenie przedramion z linkami wyciągu w opadzie',
      Odwodzenie_przedramion_z_hantlami_w_opadzie:'Odwodzenie przedramion z hantlami w opadzie',
      Dips:'Dips',
      Assisting_Machine_Dips:'Assisting Machine Dips',
      Wide_Grip_Dips:'Wide Grip Dips',
      Raised_Legs_Dips:'Raised Legs Dips',
      Close_Grip_Push_ups:'Close Grip Push-ups',
      Wyciskanie_francuskie_nad_głową_sztangi_łamanej_siedząc: 'Wyciskanie_francuskie_nad_głową_sztangi_łamanej_siedząc',
      Prostowanie_przedramion_na_wyciagu_górnym_na_linkach:'Prostowanie przedramion na wyciągu górnym na linkach',
      Prostowanie_przedramion_na_wyciągu_nad_głową_klęcząc:'Prostowanie przedramion na wyciągu nad głową klęcząc',
      Prostowanie_przedramion_na_wyciągu_nad_głową_stojąc:'Prostowanie przedramion na wyciągu nad głową stojąc',
      Prostowanie_przedramion_na_wyciągu_nad_głową_w_opadzie:'Prostowanie przedramion na wyciągu nad głową w opadzie',
      Przeciąganie_linki_wyciągu_do_przeciwległego_barku_klęcząc:'Przeciąganie linki wyciągu do przeciwległego barku klęcząc',
      Seated_Bench_French_EZ_Bar_Press_Behind_Neck:'Seated Bench French E-Z Bar Press Behind Neck',
      Bench_French_Press_Cable_Row:'Bench French Press Cable Row',
      Standing_French_Press_Cable_Row:'Standing French Press Cable Row',
      Incline_Bench_French_Press_Cable_Row:'Incline Bench French Press Cable Row',
      Wyciskanie_francuskie_na_linkach_wyciągu_podchwytem_stojąc:'Wyciskanie francuskie na linkach wyciągu podchwytem stojąc',
      Machine_Seated_French_Press:'Machine Seated French Press',
      Bench_French_E_Z_Bar_Press:'Bench French E-Z Bar Press',
      Incline_Bench_French_E_Z_Bar_Press:'Incline Bench French E-Z Bar Press',
      Decline_Bench_French_E_Z_Bar_Press:'Decline Bench French E-Z Bar Press',
      Reverse_Grip_Bench_French_E_Z_Bar_Press:'Reverse Grip Bench French E-Z Bar Press',
      Incline_Two_Arm_French_Dumbbell_Press:'Incline Two-Arm French Dumbbell Press',
      One_Arm_Seated_Dumbbell_Press:'One Arm Seated Dumbbell Press',
      Two_Arm_Seated_Dumbbell_Press:'Two Arm Seated Dumbbell Press',
      Close_Grip_Incline_Smith_Machine_Bench_Press:'Close Grip Incline Smith Machine Bench Press',
      Close_Grip_Decline_Smith_Machine_Bench_Press:'Close Grip Decline Smith Machine Bench Press',
      Close_Grip_Smith_Machine_Bench_Press:'Close Grip Smith Machine Bench Press',
      Close_Grip_Incline_Barbell_Bench_Press:'Close Grip Incline Barbell Bench Press',
      Close_Grip_Barbell_Bench_Press:'Close Grip Barbell Bench Press',
      Close_Grip_Decline_Barbell_Bench_Press:'Close Grip Decline Barbell Bench Press',
      Tate_Press_Dumbbell_Press:'Tate Press Dumbbell Press'
      // }
    },
    functional_exercises_names:{
      Burpee:'Burpee',
      MountineClimber:'Mountine Climber',
      Pompki:'Push-ups',
      Przysiady:'Squats',
      PompkinaPilce:'Pompki na piłce',
      MartwyCiagNaProstychNogach:'Stiff-Legged Deadlifts',
      PompkinaBosu:'Pompki na bosu',
      PompkinaKolanach:'Pompki na kolanach',
      Stiff_Legged_Deadlifts:'Stiff-Legged Deadlifts',
      SkipBokserski:'Skip bokserski',
      Pajacyki:'Pajacyki',
      SwingZkettlebell:'Swing z kettlebell',
      HipThrust:'Hip thrust',
      Wykroki:'Walking Lunges',
      WykrokizHantlami:'Weighted Walking Lunges',
      Lunges_with_Dumbbells:'Lunges with Dumbbells',
      Lunges_with_Barbell:'Lunges with Barbell',
      WykrokiBulgarskie:'Wykroki bułgarskie',
      WykrokizSztanga:'Lunges with Barbell',
      Skakanka:'Skakanka',
      Plank:'Plank',
      PodporBokiem:'Podpór Bokiem',
      PodporTylem:'Podpór Tyłem',
      ElbowPlankKnee:'Elbow plank knee',
      ElbowPlank:'Elbow plank',
      BasicPlank:'Basic plank',
      ExtendedPlank:'Extended plank',
      PlankLegRaise:'Plank leg raise',
      PlankArmReach:'Plank arm reach',
      BallPlank:'Ball plank',
      OverheadPress:'Overhead press',
      Squats:'Squats',
      PrzysiadyzPilkaLekarska:'Przysiady z piłką lekarską',
      KlękaniezPilka:'Klękanie z piłką',
      WchodzeniePoSchodach:'Wchodzenie po schodach',
      UnoszeniePilkiPoPrzekatnej:'Unoszenie piłki po przekątnej',
      Nozyce:'Nożyce',
      PrzysiadyNaJednejNodze:'Przysiady na jednej nodze',
          TRXprzysiadNaJednejNodze:'TRX przysiad na jednej nodze',
      TRXwyciskanie:'TRX wyciskanie',
      TRXwioslowanieTRXwyciaganieRakNadGlowe:'TRX wiosłowanie TRX wyciąganie rąk nad głowę',
      TRXwyciaganieRakNadGlowe:'TRX wyciąganie rąk nad głowę',
      TRXpodciaganieKolanPodKlatkePiersiowa:'TRX podciąganie kolan pod klatkę piersiową',
      TRXdeska:'TRX deska',
      TRXunoszenieBioderDoGory:'TRX unoszenie bioder do góry',
    },
  },
  // POLISH
  'pl-PL':{
    general:{
      reminder: 'Przypomnienie',
      regulation_acceptance_statement: 'Oświadczam, iż akceptuję regulamin aplikacji Gymgang.',
      regulation_place: 'Regulamin znajdziesz na '
    },
    clubs:{
      clubs:'Kluby',
      club:'Klub',
      my_clubs:'Moje Kluby',
      search_clubs:'Szukaj Klubów',
      name:'Nazwa',
      locale:'Lokalizacja',
      schedule: 'Godziny otwarcia',
      address:'adres',
      street:'ulica',
      city:'Miasto',
      phone:'Telefon',
      add_to_my_clubs:'Dodaj do Moich Klubów',
      delete_from_my_clubs:'Usuń z Moich Klubów',
      raiting: 'Go to raiting',
      rate: 'Ocen',
      check_in: 'Check in',
      no_more_clubs: 'Wybierz nie więcej niż 5 klubów'
    },
    week: {
      sunday: 'niedziela',
      monday: 'poniedziałek',
      tuesday: 'wtorek',
      wednesday: 'środa',
      thursday: 'czwartek',
      friday: 'piątek',
      saturday: 'sobota'
    },
    notifications:{
      notifications:'Notyfikacje'
    },
    user_card:{
      train_together:'Trenujmy Wspólnie',
      chat:'Chat',
      clubs:'Kluby',
      disciplines:'Dyscypliny',
      city:'Miasto',
      no_selected_clubs:'Brak wybranych klubów',
      friends: 'Znajomi',
      favourite: 'Ulubiony',
      tab_friends: 'Wspolni znajomi',
      tab_clubs: 'Wspólni kluby',
      achievements: 'Osiągnięcia',
      challenges: 'Wyzwania'
    },
    train_together:{
      train_together:'Trenujmy Wspólnie',
      next:'Następny',
      suggested_by:'Sugerowany po',
      club:'Po klubie',
      yes:'Tak',
      no:'Nie',
      location:'Po lokalizacji',
      suggested_workouters: 'Sugerowani trenujący'
    },
    friends:{
      friends:'Znajomi',
      my_friends:'Moi Znajomi',
      suggested_friends:'Sugerowani Znajomi',
      chat: 'Pogawędka ze Znajomymi',
      find_friends:'Szukaj Znajomych',
      add_to_friends:'Dodaj Do Znajomych',
      delete_from_my_friends:'Usuń Ze Znajomych'
    },
    muscle_parts:{
      traps:'Czworoboczne',
      shoulders:'Barki',
      chest:'Klatka piersiowa',
      biceps:'Biceps',
      triceps:'Triceps',
      forearm:'Przedramię',
      abs:'Brzuch',
      middleBack:'Środkowe grzbietu',
      lowBack:'Dolne grzbietu',
      glutes:'Pośladki',
      quads:'Czworogłowe uda',
      hamstrings:'Dwugłowe uda',
      calves:'Łydki'
    },
    body_parts:{
      body_parts:'Części ciała',
      chest:'Klatka',
      biceps:'Biceps',
      forearm:'Przedramię',
      waist:'Talia',
      belt:'Pas',
      hips:'Biodra',
      thigh:'Udo',
      calf:'Łydka',
      weight:'Waga'
    },
    drawer:{
      account:'Konto',
      settings:'Ustawienia',
      dashboard:'Panel Główny',
      train_together:'Trenujmy Wspólnie',
      workout_notes:'Notes Treningowy',
      edit_profile:'Edytuj Profil',
      clubs:'Kluby',
      shop: 'Skorzystaj ze zniżek',
      friends:'Znajomi',
      disciplines:'Edytuj Dyscypliny',
      logout:'Wyloguj się'
    },
    login:{
      password:'Hasło',
      dont_have_an_account:'Nie masz konta?',
      log_in_to_your_social_media_account:'Zaloguj za pomocą konta social media'
    },
    register:{
      password:'Hasło',
      username:'Nazwa użytkownika',
      email:'Email',
      confirmPassword:'Potwierdź Hasło',
      already_have_an_account:'Masz już konto?'
    },
    dashboard:{
      train_together:'Trenujmy Wspólnie',
      workout_notes:'Notes Treningowy',
      sport_clubs:'Kluby',
      friends:'Znajomi'
    },
    edit_profile:{
      your_profile:'Twój Profil',
      name:'Imię / Nazwisko',
      birthday:'Data urodzenia',
      gender:'Płeć',
      male:'Mężczyzna',
      female:'Kobieta',
      name_missing: 'Uzupełnij swój username',
      birthday_missing: 'Uzupełnij swoją datę urodzenia',
      warning: 'Uwaga'
    },
    disciplines:{
      disciplines:'Twoje Dyscypliny',
      gym:'Siłownia',
      basketball:'Koszykówka',
      football:'Futbol Amerykański',
      cross_fit:'Cross-fit',
      jogging:'Bieganie',
      cycling:'Kolarstwo',
      tennis:'Tenis',
      squash:'Squash',
      badminton:'Badminton',
      soccer:'Piłka nożna',
      baseball:'Baseball',
      hockey:'Hokej',
      golf:'Golf'
    },
    workout_notes:{
      workout_notes:'Notes treningowy',
      create_new_training:'Twórz trening',
      use_of_existing_training:'Użyj treningu',
      calendar_of_training:'Kalendarz treningowy',
      statistics:'Statystyki',
      cross_fit_training:'Cross Fit',
      body_measurements:'Pomiary ciała'
    },
    create_training:{
      create_training:'Twórz Trening',
      add_muscle_exercise:'Dodaj Trening Mięśniowy',
      add_cardio_exercise:'Dodaj Trening Cardio',
      functional_exercises:'Ćwiczenia Funkcjonalne',
      list_of_selected_exercises:'Wybrane Ćwiczenia',
      list_of_favourite_exercises:'Ulubione Ćwiczenia',
      save_training:'Zapisz Trening'
    },
    exercises:{
      add_to_favourites: 'Dodaj do ulubionych',
      favourite: 'Ulubione',
      add_exercise: 'Dodaj własne ćwiczenia',
      add_exercise_name: 'Wpisz nazwę ćwiczenia'
    },
    muscle_exercises:{
      muscle_exercises:'Dodaj Ćwiczenia Mięśniowe',
      muscle_part:'Partie Mięśniowe'
    },
    cardio_exercise:{
      cardio_exercise:'Dodaj Ćwiczenie Cardio',
      bike:'Rower',
      track:'Bieżnia',
      stairs:'Schody',
      elliptical: 'Orbitrek',
      intervals:'Intervals',
      rower: 'Wioslarz'
    },
    define_functional:{
      define_functional:'Określ Ćwiczenie Funkcjonalne',
      reps_count:'Liczba powtórzeń',
      time_count:'Czas (s)'
    },
    define_muscle:{
      define_muscle:'Określ Ćwiczenie Mięśniowe',
      series_count:'Liczba Serii',
      reps_count:'Ilość Powtórzeń',
      weight_count:'Ciężar (kg)',
    },
    alerts:{
        blank_training:'Trening nie może być pusty!'
    },
    define_cardio:{
      define_cardio:'Określ Ćwiczenie Cardio',
      length:'Długość',
      time:'Czas',
      level:'Poziom',
      warmUp:'Rozgrzewka',
      fastPace:'Szybkie Tempo',
      slowPace:'Wolne Tempo',
      repeats:'Powtórzenia'
    },
    calendar_of_training:{
      calendar_of_training:'Kalendarz Treningowy',
      training_name:'Nazwa Treningu'
    },
    body_measurements:{
      body_measurements:'Pomiary Ciała',
      chest:'Klatka',
      biceps:'Biceps',
      forearm:'Przedramię',
      waist:'Talia',
      belt:'Pas',
      hips:'Biodra',
      thigh:'Udo',
      calf:'Łydka',
      weight:'Waga',
      traps:'Czworoboczne',
      shoulders:'Barki',
      triceps:'Triceps',
      abs:'Brzuch',
      lats:'Motyle',
      middle_back:'Mięsnie środkowe pleców',
      lower_back:'Plecy : dolna partia',
      glutes:'Pośladki',
      quads:'Mięsień czworogłowy uda',
      hamstrings:'Uda',
      calves:'Łydki',
      date_measurement:'Data pomiaru',
      reminder: 'Nie wprowadzono jeszcze dziś pomiarów ciała.'
    },
    statistics:{
      statistics:'Statystyki',
      selected_exercises:'Wybrane Ćwiczenia',
      exercise_statistics:'Statystyki Ćwiczeń',
      cardio_statistics:'Statystyki Cardio',
      cross_fit_statistics:'Statystyki Cross Fit',
      body_measurement_statistics:'Statystyki Pomiarów Ciała',
      body_part_statistics:'Stat. Pomiarów Ciała',
      chosen_body_part:'Wybrana Część Ciała',
      chosen_exercise:'Wybrane Ćwiczenie',
      choose_exercise:'Wybierz Ćwiczenie',
      weight:'Ciężar',
      reps:'Powtórzenia',
      centimeters:'cm',
      days:'Dni'
    },
    existing_trainings:{
      existing_trainings:'Istniejące Treningi',
      edit_training: 'Edytuj ćwiczenia',
      remove_training: 'Usuń trening',
      training_removal: 'Usuwanie treningu',
      removal_confirmation: 'Czy na pewno chcesz usunąć ten trening?'
    },
    buttons:{
      save:'Zapisz',
      login:'Zaloguj się',
      signin:'Zarejestruj się',
      close:'Zamknij',
      cancel:'Anuluj',
      delete: 'Usuń',
      remove: 'Usuń'
    },
    shop:{
      click_on_ad: 'Tapnij banner, aby przejść do sklepu.',
      place_for_ad: 'Miejsce na Twoją reklamę'
    },
    muscle_exercises_names:{
      // abs:{
      bicycle_kicks:'Uginanie nóg leżąc - rowerek',
      Bent_Legs_Cross_Crunches:'Brzuszki pełne ze skrętem tułowia, ugięte nogi',
      Raised_Legs_Cross_Crunches:'Brzuszki pełne ze skrętem tułowia, ugięte nogi',
      Bent_Legs_Crunches:'Brzuszki pełne, ugięte nogi.',
      Raised_Legs_Crunches:'Brzuszki pełne, uniesione nogi',
      Decline_Bench_Crunches:'Brzuszki pełne, ławeczka ujemna',
      dotykanie_piet_lezac:'Dotykanie piet lezac',
      nozyce_lezac:'Nozyce lezac',
      odwodzenie_kolana_w_tyl_w_podparciu_przodem:'Odwodzenie kolana w tyl w podparciu przodem',
      odwodzenie_nogi_w_tyl_w_podparciu_przodem:'Odwodzenie nogi w tyl w podparciu przodem',
      odwrotne_spiecia_brzucha_uniesione_nogi:'Odwrotne spiecia brzucha uniesione nogi',
      plank:'Deska',
      przyciaganie_nog_do_klatki_piersiowej_lezac:'Przyciaganie nog do klatki piersiowej lezac',
      rowerek_spiecia_brzucha:'Rowerek spiecia brzucha',
      rowerek_spiecia_brzucha_ze_skretem_tulowia:'Rowerek spiecia brzucha ze skretem tulowia',
      scyzoryki_lezac_v_ups:'Scyzoryki lezac v ups',
      skrety_tulowia_ze_sztanga_stojac:'Skrety tulowia ze sztanga stojac',
      sklony_boczne_na_lawce_rzymskiej:'Sklony boczne na lawce rzymskiej',
      sklony_boczne_z_linka_wyciagu_stojac:'Sklony boczne z linka wyciagu stojac',
      Sklony_boczne_z_hantlami_stojac:'Sklony boczne z hantlami stojac',
      spiecia_brzucha_laweczka_ujemna:'Spiecia brzucha laweczka ujemna',
      spiecia_brzucha_bokiem_na_maszynie_siedzac:'Spiecia brzucha bokiem na maszynie siedzac',
      spiecia_brzucha_lezac_bokiem:'Spiecia brzucha lezac bokiem',
      spiecia_brzucha_na_maszynie_siedzac:'Spiecia brzucha na maszynie siedzac',
      spiecia_brzucha_na_wyciagu_stojac:'Spiecia brzucha na wyciagu stojac',
      spiecia_brzucha_z_podpaciem_nog_lezac:'Spiecia brzucha z podpaciem nog lezac',
      spiecia_brzucha_z_podparciem_nog_lezac_bokiem:'Spiecia brzucha z podparciem nog lezac bokiem',
      spiecia_brzucha_ugiete_nogi:'Spiecia brzucha ugiete nogi',
      spiecia_brzucha_uniesione_nogi:'Spiecia brzucha uniesione nogi',
      toczenie_sztangi_kleczac:'Toczenie sztangi kleczac',
      unoszenie_bioder_nogi_w_gorze_lezac:'Unoszenie bioder nogi w gorze lezac',
      unoszenie_bioder_ugiete_nogi_lezac:'Unoszenie bioder ugiete nogi lezac',
      unoszenie_kolan_w_zwisie:'Unoszenie kolan w zwisie',
      unoszenie_nog_lezac:'Unoszenie nog lezac',
      unoszenie_nog_w_zwisie:'Unoszenie nog w zwisie',
      unoszenie_tulowia_z_nogami_w_gorze_lezac:'Unoszenie tulowia z nogami w gorze lezac',
      sciaganie_linki_wyciagu_gornego_prz_prostych_lokciach_stojac:'Sciaganie linki wyciagu gornego prz prostych lokciach stojac',
      // },
      // biceps:{
      incline_hammer_curls:'Uginanie ramion ze sztangielkami leżąc – skos w górę (uchwyt młotkowy) ',
      incline_inner_biceps_curl:'Uginanie ramion ze sztangielkami leżąc – skos w górę (uchwyt zwykły) ',
      standing_concentration_curl:'Uginanie ramienia ze sztangielką w pozycji stojącej pochylonej ',
      ez_bar_curl:'Uginanie ramion ze sztangą łamaną stojąc',
      wide_grip_standing_barbell_curl:'Uginanie ramion szeroko ze sztangą prostą stojąc',
      zottman_curl:'Uginanie ramion z hantlami typu Zottman stojąc',
      barbell_curl:'Uginanie ramion ze sztangą stojąc',
      dumbbell_biceps_curl:'Uginanie ramion z hantlami ',
      hammer_curl:'Uginanie ramion z hantlami „młotkowe”',
      overhead_cable_curl:'Uginanie ramion nad głową stojąc z linką na maszynie',
      Seated_Alternate_Reverse_Grip_Dumbbell_Curls:'Naprzemienne uginanie przedramion z hantlami podchwytem siedząc',
      Standing_Alternate_Reverse_Grip_Dumbbell_Curls:'Naprzemienne uginanie przedramion z hantlami podchwytem stojac',
      Alternate_Dumbbell_Hammer_Curls:'Naprzemienne uginanie przedramion z hantlami w chwycie młotkowym',
      Medium_Overhand_Grip_Pull_up:'Podciąganie nachwytem średni rozstaw rąk',
      Assisting_Machine_Medium_Overhand_Grip_Pull_up:'Podciąganie nachwytem na maszynie z asystą średni rozstaw rąk',
      Medium_Underhand_Grip_Pull_up:'Podciąganie podchwytem średni rozstaw rąk',
      Assisting_Machine_Medium_Underhand_Grip_Pull_up:'Podciąganie podchwytem na maszynie z asystą średni rozstaw rąk',
      Close_Overhand_Grip_Pull_up:'Podciąganie nachwytem wąski rozstaw rąk',
      Single_arm_Dumbbell_Curl:'Uginanie pojedynczego przedramienia z hantlem',
      Cross_Body_Cable_Curls:'Uginanie przedramienia do przeciwległego barku z linkami wyciągu',
      Standing_Cross_Body_Dumbbell_Curls:'Uginanie przedramienia z hantlami do przeciwległego barku stojąc',
      Seated_Cross_Body_Dumbbell_Curls:'Uginanie przedramienia z hantlem do przeciwległego barku siedząc',
      Seated_Machine_Reverse_Grip_Curls:'Uginanie przedramienia na maszynie podchwytem siedząc',
      Scotts_Machine_Preacher_Curls:'Uginanie przedramion na modlitewniku maszynie scotta siedząc',
      Standing_Over_Head_Cable_Curls:'Uginanie przedramion nad głową z linkami wyciągu górnego stojąc',
      Lying_Cable_Curls:'Uginanie przedramion z linkami wyciągu dolnego leżąc',
      Standing_Cable_Curls:'Uginanie przedramion z linkami wyciągu dolnego stojąc',
      Preacher_Cable_Curls:'Uginanie przedramion z linkami wyciągu dolnego na modlitewniku',
      Incline_Bench_Cable_Curls:'Uginanie przedramion z linkami wyciągu dolnego na ławce dodatniej',
      Bench_Cable_Curls:'Uginanie przedramion z linkami wyciągu dolnego na ławce poziomej',
      Standing_Hammer_Curl:'Uginanie przedramion z hantlami w chwycie młotkowym stojąc',
      Dumbbel_Preacher_Curl:'Uginanie przedramion z hantlami na modlitewniku w chwycie młotkowym',
      Dumbbell_Prone_Incline_Curl:'Uginanie przedramion z hantlami na ławce leżąc przodem',
      Incline_Seated_Dumbbell_Curl:'Uginanie przedramion z hantlami na ławce dodatniej',
      Seated_Reverse_Grip_Curls:'Uginanie przedramion z hantlami podchwytem siedząc',
      Standing_Reverse_Dumbbell_Curl:'Uginanie przedramion z hantlami stojąc???',
      Standing_Wide_Grip_EZ_Barbell_Curls:'Uginanie przedramion ze sztangą łamaną szeorki rozstaw rąk stojąc',
      Preacher_Barbell_Curl:'Uginanie przedramion ze sztangą na modlitewniku siedząc',
      Barbell_Prone_Incline_Curls:'Uginanie przedramion ze sztangą na ławce leżąc przodem',
      Incline_Seated_Barbell_Curl:'Uginanie przedramion ze sztangą na ławce dodatniej',
      Standing_Barbell_Curl:'Uginanie przedramion ze sztangą podchwytem stojąc',
      EZ_Bar_Preacher_Curl:'Uginanie przedramion ze sztangą łamaną na modlitewniku siedząc',
      Standing_Reverse_Grip_EZ_Bar_Curls:'Uginanie przedramion ze sztangą łamaną podchwytem stojąc',
      Standing_Close_Grip_EZ_Bar_Curls:'Uginanie przedramion ze sztangą łamaną wąski rozstaw rąk stojąc',
      Standing_Wide_Grip_EZ_Bar_Curls:'Uginanie przedramion ze sztangą łamaną szeroki rozstaw rąk stojąc',
      Standing_Close_Grip_Barbell_Curls:'Uginanie przedramion ze sztangą wąski rozstaw rąk stojąc',
      Standing_Upright_Dumbbell_Row:'Wiosłowanie hantlami wzdłuż tułowia stojąc',
      Standing_Upright_Barbell_Row:'Wiosłowanie sztangą wzdłuż tułowia stojąc',
      Standing_Upright_Cable_Row:'Wiosłowanie wzdłuż tułowia na wyciągu stojąc',
      Standing_Upright_Smith_Machine_Barbell_Row:'Wiosłowanie wzdłuż tułowia sztangą na suwnicy smitha stojąc',
      sciaganie_drazka_wyciagu_gornego_do_klatki_piersiowej_nadchwytem_waski:'Sciaganie drazka wyciagu gornego do klatki piersiowej nadchwytem waski',
      sciaganie_drazka_wyciągu_gornego_do_klatki_piersiowej_podchwytem_waski:'Sciaganie drazka wyciągu gornego do klatki piersiowej podchwytem waski',
      // },
      // chest:{
      Barbell_bench_press:'Wyciskanie sztangi leżąc na ławce',
      Flat_bench_dumbbell_press:'Wyciskanie hantli leżąc, ławka ujemna',
      Low_incline_barbell_bench_press:'Wyciskanie sztangi leżąc na ławce skosem w górę',
      Machine_decline_press:'Wyciskanie sztangi leżąc na ławce skosem w dół na maszynie',
      Seated_machine_chest_press:'Wyciskanie sztangi siedząc na maszynie',
      Incline_dumbbell_press:'Wyciskanie hantlami leżąc',
      Dips_for_chest:'Rozpiętki',
      Incline_bench_cable_fly:'Rozpiętki z linkami na ławce dodatniej',
      Incline_dumbbell_pull_over:'Przenoszenie hantli nad głową leżąc na ławce – skos w górę',
      Pec_deck_machine:'Motylki na maszynie',
      Standing_Cable_Crossovers:'Krzyżowanie linek wyciągu stojąc',
      Assisting_Machine_Dips:'Pompki szwedzkie na maszynie z asystą',
      Wide_Grip_Bent_Over_Dips:'Pompki szwedzkie w opadzie szeroki rozstaw rąk',
      Handrail_Bent_Over_Dips:'Pompki szwedzkie na poręczach w opadzie',
      Wide_Grip_Push_ups_with_Leg_on_Suspension:'Pompki z nogami na podwieszeniu szeroki rozstaw rąk',
      Wide_Grip_Push_ups:'Pompki szeroki rozstaw rąk',
      Przeciąganie_linek_wyciągu_za_głowę:'Przeciąganie linek wyciągu za głowę',
      Przenoszenie_sztangi_za_głowę:'Przenoszenie sztangi za głowę',
      Przenoszenie_sztangi_łamanej_za_głowę:'Przenoszenie sztangi łamanej za głowę',
      Przenoszenie_hantli_za_głowę:'Przenoszenie hantli za głowę',
      Rozpiętki_na_maszynie_ramiona_wyprostowane_siedząc:'Rozpiętki na maszynie ramiona wyprostowane siedząc',
      Incline_Bench_Cable_Flys:'Rozpiętki z linkami na ławce dodatniej',
      Pec_Dec_Seated_Machine_Flys:'Rozpiętki na maszynie, ramiona zgięte siedząc',
      Decline_Bench_Cable_Flys:'Rozpiętki z linkami na ławce ujemnej',
      Incline_Dumbbell_Flys:'Rozpiętki z hantlami na ławce dodatniej',
      Dumbbell_Flys:'Rozpiętki z hantlami na ławce poziomej',
      Decline_Dumbbell_Flys:'Rozpiętki z hantlami na ławce ujemnej',
      Incline_Dumbbell_Flys_with_Supination:'Rozpiętki z hantlami z supinacją na ławce dodatniej',
      Dumbbell_Flys_with_Supination:'Rozpiętki z hantlami z supinacją na ławce poziomej',
      Decline_Dumbbell_Flys_with_Supination:'Rozpiętki z hantlami z supinajcą na ławce ujemnej',
      Front_Seated_Machine_Press:'Wyciskanie do przodu na maszynie siedząc',
      Incline_Machine_Press:'Wyciskanie na maszynie na ławce dodatniej',
      Machine_Press:'Wyciskanie na maszynie na ławce poziomej',
      Decline_Machine_Press:'Wyciskanie na maszynie na ławce ujemnej',
      Wide_Grip_Incline_Smith_Machine_Bench_Press:'Wyciskanie na suwnicy smitha na ławce dodatniej szeroki uchwyt',
      Wide_Grip_Smith_Machine_Bench_Press:'Wyciskanie na suwnicy smitha na ławce poziomej szeroki uchwyt',
      Wide_Grip_Decline_Smith_Machine_Bench_Press:'Wyciskanie na suwnicy smitha na ławce ujemnej szeroki uchwyt',
      Incline_Smith_Machine_Bench_Press:'Wyciskanie na suwnicy smitha na ławce dodatniej',
      Smith_Machine_Bench_Press:'Wyciskanie na suwnicy smitha na ławce poziomej',
      Decline_Smith_Machine_Bench_Press:'Wyciskanie na suwnicy smitha na ławce ujemnej',
      Wide_Grip_Incline_Barbell_Bench_Press:'Wyciskanie sztangi na ławce dodatniej szeroki rozstaw rąk',
      Decline_Barbell_Bench_Press:'Wyciskanie sztangi leżąc na ławce skosem w dół na maszynie',
      Wide_Grip_Decline_Barbell_Bench_Press:'Wyciskanie sztangi na ławce ujemnej szeroki rozstaw rąk',
      Palms_in_Incline_Dumbbell_Bench_Press:'Wyciskanie hantli chwytem młotkowym na ławce dodatniej',
      Palms_in_Dumbbell_Bench_Press:'Wyciskanie hantlii chwytem młotkowym na ławce poziomej',
      Palms_in_Decline_Dumbbell_Bench_Press:'Wyciskanie hantlii chwytem młotkowym na ławce ujemnej',
      Incline_Seated_Dumbell_Press:'Wyciskanie hantli na ławce dodatniej',
      Dumbbell_Bench_Press:'Wyciskanie hantli chwytem młotkowym na ławce dodatniej',
      Decline_Dumbbel_Bench_Press:'Wyciskanie hantlii na ławce ujemnej',
      // },
      // calves:{
      Standing_machine_calf_raises:'Wspięcia na palcach na maszynie stojąc – łydki',
      Smith_machine_calf_raises:'Łydki na maszynie Smith’a',
      One_legged_dumbbell_calf_raises:'Łydki na jednej nodze z cięzarkiem',
      Leg_press_calf_raise:'Wypychanie ciężaru na suwnicy ',
      Seated_machine_calf_raises:'Wspięcia na palcach na maszynie siedzącstojąc – łydki',
      Wspięcia_na_palce_ze_sztangą_siedząc:'Wspięcia na palce ze sztangą siedząc',
      Wspięcia_na_palce_ze_sztangą_stojąc:'Wspięcia na palce ze sztangą stojąc',
      // },
      // forearm:{
      Barbell_wrist_curls:'Zginanie nadgarstków ze sztangą',
      Barbell_reverse_wrist_curls:'Odwrotne zginanie nadgarstków ze sztangą nachwytem',
      Dumbbell_wrist_curl:'Zginanie nadgarstków z hantlami',
      Dumbbell_reverse_wrist_curl:'Odwrotne zginanie nadgarstków z hantlami nachwytem',
      Reverse_barbell_curls:'Uginanie ramion stojąc ze sztangą nachwytem',
      Standing_Wrist_Cable_Reverse_Curls:'Odwrotne uginanie nagrastków na linkach wyciągu stojąc ',
      Standing_Reverse_Wrist_Curls_with_Barbell_Plate:'Odwrotne uginanie nadgarstków z talerzem do sztangi stojąc',
      Standing_Barbell_Reverse_Wrist_Curls:'Odwrotne uginanie nadgarstków ze sztangą stojąc',
      Podciąganie_się_nadchytem_wąski_rozstaw_rąk:'Podciąganie się nadchytem wąski rozstaw rąk',
      Seated_Lateral_Wrist_Cable_Curls:'Uginanie nagrastków bokiem na linkach wyciągu siedząc',
      Standing_Wrist_Cable_Curls:'Uginanie nadgarstków na linkach wyciągu stojąc',
      Seated_Underhand_Dumbbell_Wrist_Curls:'Uginanie nadgarstków z hantlami podchwytem siedząc',
      Seated_Underhand_Barbell_Wirst_Curls:'Uginanie nadgarstków ze sztanką podchwytem siedząc',
      Standing_Underhand_Barbell_Wrist_Curls:'Uginanie nadgarstków ze sztangą podchwytem stojąc',
      Standing_Underhand_Behind_Barbell_Wirst_Curls:'Uginanie nadgarstków ze sztangą za plecami podchwytem stojąc',
      Uginanie_nadgarstków_ze_sztangą_łamaną_podchwytem_siedząc:'Uginanie nadgarstków ze sztangą łamaną podchwytem siedząc',
      Seated_Underhand_EZ_Bar_Wrist_Curls:'Uginanie nadgarstków ze sztangą łamaną podchwytem siedząc',
      // },
      // glutes:{
      squats:'Przysiady',
      Weighted_Walking_Lunges:'Wykroki z hantlami',
      Barbell_Hip_Thrusts:'Wyciskanie sztangi biodrami leżąc na ławce ',
      Stiff_Legged_Deadlifts:'Martwy ciąg na prostych nogach',
      Bulgarian_Split_Squats:'Bułgarskie przysiady',
      Wide_Stand_Barbell_Sumo_Deadlift:'Martwy ciąg sumo ze sztangą szeroki rozstaw nóg',
      Dumbbell_Deadlift:'Martwy ciąg z hantlami',
      Barbell_Deadlift:'Martwy ciąg ze sztangą',
      Cable_Deadlift:'Martwy ciąg z linkami wyciągu',
      Nożyce_leżąc:'Nożyce leżąc',
      odwodzenie_nogi_w_tył_klęcząc:'Odwodzenie nogi w tył klęcząc',
      Odwodzenie_nogi_w_tył_na_maszynie:'Odwodzenie nogi w tył na maszynie',
      Odwodzenie_nogi_w_tył_ze_zgięciem_kolana_klęcząc:'Odwodzenie nogi w tył ze zgięciem kolana klęcząc',
      Odwodzenie_nogi_z_linką_wyciągu_stojąc:'Odwodzenie nogi z linką wyciągu stojąc',
      Odwodzenie_nóg_na_maszynie_siedząc:'Odwodzenie nóg na maszynie siedząc',
      Przeciąganie_linki_wyciągu_stojąc:'Przeciąganie linki wyciągu stojąc',
      Laverage_Machine_Standing_Squats:'Przysiady na maszynie leverage stojąc',
      Incline_Bench_Machine_Squats:'Przysiady na maszynie na ławce dodatniej',
      Smith_Machine_Standing_Front_Squats:'Przysiady z obciążeniem z przodu na suwnicy smitha stojąc',
      Kneeling_Barbell_Squats:'Przysiady ze sztangą klęcząc',
      Deep_Squat:'Przysiady ze sztangą na barkach',
      Standing_Neck_Barbell_Squats:'Przysiady ze sztangą na karku stojąc',
      Back_Squats:'Przysiady ze sztangą z tyłu',
      Seated_Machine_Legs_Adduction:'Przywodzenie nóg na maszynie siedząc',
      Standing_Barbell_Back_Curls:'Uginanie pleców ze sztangą stojąc',
      Unoszenie_bioder_ugięte_nogi_leżąc:'Unoszenie bioder ugięte nogi leżąc',
      Weighted_Walking_Lunges:'Wykroki z hantlami',
      Lunges_with_Barbell:'Wykroki ze sztangą',
      Incline_Press_Machine_Leg_Press:'Wypychanie ciężaru nogami na suwnicy na ławce dodatniej',
      // },
      // hamstrings:{
      clean_deadlift:'Martwy ciąg czysty',
      romanian_deadlift_from_deficit:'Rumuński martwy ciąg', // problem
      kettlebell_one_legged_deadlift:'Martwy ciąg na jednej nodze z ciężarkiem',
      power_snatch:'Rwanie',
      hang_snatch:'Rwanie z kolan',
      floor_glute_ham_raise:'Żuraf',
      power_clean_from_blocks:'Podnoszenie sztangi z podstawki',
      lying_leg_curls:'Uginanie nóg w leżeniu ',
      sumo_deadlift:'Martwy ciąg „sumo”',
      Standing_Cable_Leg_Curls:'Uginanie nogi z linką wyciągu dolnego stojąc',
      Front_Lying_Machine_Legs_Curls:'Uginanie nóg na maszynie leżąc przodem',
      Seated_Machine_Legs_Curls:'Uginanie nóg na maszynie siedząc ',
      Standing_Machine_Legs_Curls:'Uginanie nóg na maszynie stojąc',
      // },
      // lats:{
      Leverage_iso_row:'Wiosłowanie na maszynie siedząc',
      Wide_grip_lat_pull_down:'Ciąganie linki wyciągu górnego szeroko',
      Underhand_cable_pull_down:'Ściąganie linki wyciągu górnego podchwytem',
      Straight_arm_pull_down:'Ściąganie linki wyciągu górnego nachwytem na prostych ramionach',
      V_bar_pull_down:'Ściąganie linki wyciągu górnego z uchwytem V.',
      Close_grip_front_lat_pull_down:'Ściąganie linki wyciągu górnego wąsko',
      V_bar_pull_up:'Podciąganie się na drążku z uchwytem V',
      Rocky_pull_up:'Podciąganie się na drążku z uchwytem V',
      Chin_up:'Podciąganie się na drążku podbródkiem nad drążek',
      // },
      // lowBack:{
      Wide_Stand_Barbell_Sumo_Deadlift:'Martwy ciąg sumo ze sztangą szeroki rozstaw nóg',
      Dumbbell_Deadlift:'Martwy ciąg z hantlami',
      Barbell_Deadlift:'Martwy ciąg ze sztangą',
      Cable_Deadlift:'Martwy ciąg z linkami wyciągu',
      Prostowanie_grzbietu_na_maszynie:'Prostowanie grzbietu na maszynie',
      Prostowanie_grzbietu_na_maszynie_siedząc:'Prostowanie grzbietu na maszynie siedząc',
      Prostowanie_grzbietu_na_ławce_poziomej_leżąc_przodem:'Prostowanie grzbietu na ławce poziomej leżąc przodem',
      Przeciąganie_linki_wyciągu_stojąc:'Przeciąganie linki wyciągu stojąc',
      Laverage_Machine_Standing_Squats:'Przysiady na maszynie leverage stojąc',
      Kneeling_Barbell_Squats:'Przysiady ze sztangą klęcząc',
      Standing_Deep_Squat:'Przysiady ze sztangą na barkach stojąc',
      Standing_Neck_Barbell_Squats:'Przysiady ze sztangą na karku stojąc',
      Front_Lying_Back_Curls:'Uginanie pleców leżąc na brzuchu',
      Seated_Barbell_Back_Curls:'Uginanie pleców ze sztangą siedząc',
      Standing_Barbell_Back_Curls:'Uginanie pleców ze sztangą stojąc',
      // },
      // middleBack:{
      Barbell_deadlift:'Martwy ciąg ze sztangą',
      Bent_over_barbell_deadlift:'Martwy ciąg w opadzie',
      Wide_grip_pull_up:'Podciąganie się na drążku szeroko',
      Standing_t_bar_row:'Wiosłowanie półsztangą',
      Wide_grip_seated_cable_row:'Ściąganie linki wyciągu dolnego szeroko',
      Reverse_grip_smith_machine_row:'Wiosłowanie na maszynie Smith podchwytem stojąc',
      Close_grip_pull_down:'Ściąganie linki wyciągu górnego wąsko',
      Single_arm_dumbbell_row:'Wiosłowanie hantla w oparciu kolanem o ławkę',
      Decline_bench_dumbbell_pull_over:'Przenoszenie hantli nad głową leżąc na ławce – skos w dół',
      Single_arm_smith_machine_row:'Wiosłowanie jedną rękę na maszynie Smith’a',
      Medium_Overhand_Grip_Pull_up:'Podciąganie nachwytem średni rozstaw rąk',
      Assisting_Machine_Wide_Overhand_Grip_Pull_up:'Podciąganie nachwytem na maszynie z asystą szeroki rozstaw rąk',
      Assisting_Machine_Medium_Overhand_Grip_Pull_up:'Podciąganie nachwytem na maszynie z asystą średni rozstaw rąk',
      Wide_Underhand_Grip_Pull_up:'Podciąganie podchwytem na maszynie z asystą szeroki rozstaw rąk',
      Medium_Underhand_Grip_Pull_up:'Podciąganie podchwytem średni rozstaw rąk',
      Assisting_Machine_Close_Underhand_Grip_Pull_up:'Podciąganie podchwytem na maszynie z asystą wąski rozstaw rąk',
      Assisting_Machine_Medium_Underhand_Grip_Pull_up:'Podciąganie podchwytem na maszynie z asystą średni rozstaw rąk',
      Assisting_Machine_Wide_Underhand_Grip_Pull_up:'Podciąganie podchwytem na maszynie z asystą szeroki rozstaw rąk',
      Wide_Overhand_Grip_Pull_up:'Podciąganie nachwytem szeroki rozstaw rąk',
      Tipup_ze_sztangą_w_opadzie_stojąc:'Tipup ze sztangą w opadzie stojąc',
      Leverage_Machine_Seated_Row:'Wiosłowanie na maszynie leverage siedząc',
      Seated_Cable_Row:'Wiosłowanie na wyciągu poziomym siedząc',
      Decline_Seated_Cable_Row:'Wiosłowanie na wyciągu w opadzie siedząc',
      Bench_Dumbbell_Row_Front_Lying:'Wiosłowanie hantlami na ławce poziomej leżąc przodem',
      Bent_Over_Dumbbell_Row:'Wiosłowanie hantlami w opadzie',
      Smith_Machine_Standing_Bent_Over_Row:'Wiosłowanie sztangą na suwnicy smitha w opadzie stojąc',
      Bench_Barbell_Row_Front_Lying:'Wiosłowanie sztangą na ławce poziomej leżąc przodem',
      Reverse_Grip_Bent_Over_Barbell_Rows:'Wiosłowanie sztangą podchwytem w opadzie stojąc',
      Bent_Over_Barbell_Row:'Wiosłowanie sztangą w opadzie',
      Ściąganie_droążka_wyciągu_górnego_do_karku_szeroki_rozstaw_rąk_siedząc:'Ściąganie drążka wyciągu górnego do karku szeroki rozstaw rąk siedząc',
      Ściąganie_drażka_wyciągu_górnego_do_klatki_piersiowej_nadchwytem_wąski_rozstaw_rąk:'Ściąganie drażka wyciągu górnego do klatki piersiowej nadchwytem wąski rozstaw rąk',
      Ściąganie_drążka_wyciągu_górnego_do_klatki_piersiowej_podchwytem_wąski_rozstaw_rąk:'Ściąganie drążka wyciągu górnego do klatki piersiowej podchwytem wąski rozstaw rąk',
      Ściąganie_drążka_wyciągu_górnego_do_klatki_piersiowej_szeroki_rozstaw_rąk:'Ściąganie drążka wyciągu górnego do klatki piersiowej szeroki rozstaw rąk',
      Ściąganie_na_maszynie_leverage_siedząc:'Ściąganie na maszynie leverage siedząc',
      // },
      // quads:{
      Box_squat_with_bands:'Przysiady ze sztanga i gumami',
      Barbell_lunge:'Przysiady wykroczne ze sztangą',
      Narrow_stance_squats:'Przysiady w wąskiej postawie',
      Goblet_squat:'Przysiad z obciążeniem trzymanym oburącz na wysokości mostka',
      Frankenstein_squat:'Przysiad Frankensteina – z wyprostowanymi ramionami',
      Box_squat:'Przysiad do skrzyni',
      Kettlebell_pistol_squat:'Przysiad z ciężarkiem na jednej nodze',
      Front_squat_clean_grip:'Przysiady ze sztanga z przodu',
      Barbell_squat:'Przysiady ze sztanga z tyłu',
      Front_squats_with_two_kettlebells:'Przysiady z dwoma ciężarkami z przodu',
      Dynamiczne_podskoki:'Dynamiczne podskoki',
      Dumbbell_Deadlift:'Martwy ciąg z hantlami',
      Barbell_Deadlift:'Martwy ciąg ze sztangą',
      Cable_Deadlift:'Martwy ciąg z linkami wyciągu',
      Odwodzenie_nóg_na_maszynie_siedząc:'Odwodzenie nóg na maszynie siedząc',
      Odwodznie_nóg_na_maszynie_stojąc:'Odwodznie nóg na maszynie stojąc',
      Prostowanie_nóg_na_maszynie_siedząc:'Prostowanie nóg na maszynie siedząc',
      Laverage_Machine_Standing_Squats:'Przysiady na maszynie leverage stojąc',
      Incline_Bench_Machine_Squats:'Przysiady na maszynie na ławce dodatniej',
      Smith_Machine_Standing_Front_Squats:'Przysiady z obciążeniem z przodu na suwnicy smitha stojąc',
      Smith_Machine_Standing_Back_Squats:'Przysiady z obciążeniem z tyłu na suwnicy smitha stojąc',
      Deep_Squat:'Przysiady ze sztangą na barkach',
      Standing_Neck_Barbell_Squats:'Przysiady ze sztangą na karku stojąc',
      Back_Squats:'Przysiady ze sztangą z tyłu',
      Seated_Machine_Legs_Adduction:'Przywodzenie nóg na maszynie siedząc',
      Standing_Machine_Legs_Adduction:'Przywodzenie nóg na maszynie stojąc',
      Step_with_Dumbbells:'Step z hantlami',
      Step_with_Barbell:'Step ze sztangą',
      Lunges_with_Barbell:'Wykroki ze sztangą',
      Lunges_with_Bag:'Wykroki z workiem',
      Lunges_with_Dumbbells:'Wykroki z hantlami',
      Incline_Press_Machine_Leg_Press:'Wypychanie ciężaru nogami na suwnicy na ławce dodatniej',
      // },
      // shoulders:{
      Cable_reverse_flye:'Ściąganie linek po skosie na bramie',
      Hand_standPush_ups:'Hand-stand_Push-ups',
      Bent_over_dumbbell_lateral_raise:'Unoszenie sztangielek bokiem w górę w poz. pochylonej do przodu',
      One_arm_cable_lateral_raise:'Unoszenie ramiona bokiem w górę na maszynie (wyciąg)',
      Cable_front_raise:'Unoszenie ramion przodem w górę na maszynie (wyciąg)',
      Push_press:'Wyciskanie sztangi stojąc',
      Wide_grip_smith_machine_upright_row:'Podciąganie sztangi szeroko na maszynie Smith’a stojąc',
      Face_pull:'Odwodzenie ramion w tył na wyciągu górnym stojąc',
      Dumbbell_lateral_raise:'Unoszenie sztangielek bokiem w górę(latanie)',
      Seated_barbell_shoulder_press:'Wyciskanie sztangi siedząc',
      Seated_dumbbell_shoulder_press:'Wyciskanie hantli siedząc',
      Machine_Reverse_Dumbbell_Flys:'Odwrotne rozpiętki na maszynie leżąc',
      Seated_Machine_Reverse_Dumbbell_Flys:'Odwrotne rozpiętki na maszynie siedząc',
      Front_Reverse_Dumbbell_Flys:'Odwrotne rozpietki z hantlami na ławce poziomej leżąc przodem',
      Hand_stand_Push_ups:'Pompki w staniu na rękach',
      Standing_Single_arm_Front_Cable_Raise:'Unoszenie pojedyńczego ramienia przodem z linką wyciągu stojąc',
      Leaning_Dumbbel_Lateral_Raise:'Unoszenie ramion bokiem z hantlami w opadzie',
      Standing_Front_Cable_Raise:'Unoszenie ramion przodem z linką wyciągu stojąc',
      Standing_Barbell_Plate_Front_Raise:'Unoszenie ramion przodem z talerzem do sztangi stojąc',
      Standing_Dumbbell_Front_Raise:'Unoszenie ramion przodem z hantlami stojąc',
      Standing_Barbell_Front_Raise:'Unoszenie ramion przodem ze sztangą stojąc',
      Cable_Lateral_Raise:'Unoszenie ramion bokiem z linkami wyciągu dolnego w opadzie',
      Standing_Upright_Barbell_Row:'Wiosłowanie sztangą wzdłuż tułowia stojąc',
      Standing_Upright_Cable_Row:'Wiosłowanie wzdłuż tułowia na wyciągu stojąc',
      Standing_Upright_Smith_Machine_Barbell_Row:'Wiosłowanie wzdłuż tułowia sztangą na suwnicy smitha stojąc',
      Wyciskanie_sprzed_głowy_na_maszynie_siedząc:'Wyciskanie sprzed głowy na maszynie siedząc',
      Wyciskanie_sprzed_głowy_na_suwnicy_Smitha_siedząc:'Wyciskanie sprzed głowy na suwnicy Smitha siedząc',
      Standing_Back_Barbell_Press:'Wyciskanie sztangi sprzed głowy stojąc',
      Standing_Barbell_Press_Behind_Neck:'Wyciskanie sztangi zza głowy stojąc',
      Incline_Seated_Dumbell_Press:'Wyciskanie hantli na ławce dodatniej',
      Seated_Dumbell_Press:'Wyciskanie hantlii sprzed głowy stojąc',
      // },
      // traps:{
      Barbell_shrug:'Szrugsy sztangą',
      Barbell_shrug_behind_the_back:'Szrugsy ze sztangą z tyłu',
      Cable_shrugs:'Szrugsy na maszynie wyciąg dolny',
      Calf_machine_shoulder_shrug:'Szrugsy na maszynie do wspięć',
      Clean_shrug:'Szrugsy',
      Dumbbell_shrug:'Szrugsy hantlami',
      Kettlebell_sumo_high_pull:'Podnoszenie ciężarka Giria wysoko w poz. sumo',
      Leverage_shrug:'Szrugsy na maszynie z uchwytem z tyłu',
      Scapular_pull_up:'Podciaganie na drążku',
      Smith_machine_behind_the_back_shrug:'Szrugsy na maszynie smitha z tyłu',
      Smith_machine_shrug:'Szrugsy na maszynie smitha',
      Smith_machine_upright_row:'Unoszenie sztangi do brody na maszynie smitha',
      Snatch_shrug:'Szrugsy z rwaniem sztangi do podbrudka',
      Standing_dumbbell_upright_row:'Podciąganie hantli wzdłuż tułowia',
      Upright_cable_row:'Unoszenie ramion w przód z linkami wyciągu',
      Upright_row_with_bands:'Unoszenie ramion w przód przy użyciu gumy',
      // },
      // triceps: {
      Dumbbell_rollbacks:'Prostowanie lokci lezac na lawce uchwyt mlotkowy zza głowy',
      Board_close_grip_bench_press:'Wyciskanie sztangi wąsko leżąc na ławce',
      Kickbacks_with_a_twist:'Prostowanie łokcia w opadzie trzymając hantle w uchwycie mlotkowym',
      Rep_hold_push_downs:'Ściąganie linki w dól prostując łokcie- maszyna',
      Odwodzenie_przedramion_z_linkami_wyciągu_w_opadzie:'Odwodzenie przedramion z linkami wyciągu w opadzie',
      Odwodzenie_przedramion_z_hantlami_w_opadzie:'Odwodzenie przedramion z hantlami w opadzie',
      Dips:'Pompki Szwedzkie',
      Assisting_Machine_Dips:'Pompki szwedzkie na maszynie z asystą',
      Wide_Grip_Dips:'Pompki szwedzkie szeroki rozstaw rąk',
      Raised_Legs_Dips:'Pompki szwedzkie uniesione nogi',
      Close_Grip_Push_ups:'Pompki wąski rozstaw rąk',
      Clos_Grip_Decline_Barbell_Bench_Press: 'Wyciskanie sztangi na ławce leżąc, wąski chwyt',
      Wyciskanie_francuskie_nad_głową_sztangi_łamanej_siedząc: 'Wyciskanie francuskie nad głową sztangi łamanej siedząc',
      Prostowanie_przedramion_na_wyciagu_górnym_na_linkach:'Prostowanie przedramion na wyciągu górnym na linkach',
      Prostowanie_przedramion_na_wyciągu_nad_głową_klęcząc:'Prostowanie przedramion na wyciągu nad głową klęcząc',
      Prostowanie_przedramion_na_wyciągu_nad_głową_stojąc:'Prostowanie przedramion na wyciągu nad głową stojąc',
      Prostowanie_przedramion_na_wyciągu_nad_głową_w_opadzie:'Prostowanie przedramion na wyciągu nad głową w opadzie',
      Przeciąganie_linki_wyciągu_do_przeciwległego_barku_klęcząc:'Przeciąganie linki wyciągu do przeciwległego barku klęcząc',
      Seated_Bench_French_EZ_Bar_Press_Behind_Neck:'Wyciskanie francuskie nad głową sztangi łamanej siedząc',
      Bench_French_Press_Cable_Row:'Wyciskanie francuskie linki wyciągu dolnego leżąc',
      Standing_French_Press_Cable_Row:'Wyciskanie francuskie linki wyciąganu dolnego stojąc',
      Incline_Bench_French_Press_Cable_Row:'Wyciskanie francuskie linki wyciągu dolnego na ławce dodatniej',
      Wyciskanie_francuskie_na_linkach_wyciągu_podchwytem_stojąc:'Wyciskanie francuskie na linkach wyciągu podchwytem stojąc',
      Machine_Seated_French_Press:'Wyciskanie francuskie na maszynie siedząc',
      Bench_French_E_Z_Bar_Press:'Wyciskanie francuskie sztangi łamanej leżąc',
      Seated_Bench_French_EZ_Bar_Press_Behind_Neck:'Wyciskanie francuskie nad głową sztangi łamanej siedząc',
      Incline_Bench_French_E_Z_Bar_Press:'Wyciskanie francuskie sztangi łamanej na ławce dodatniej',
      Decline_Bench_French_E_Z_Bar_Press:'Wyciskanie francuskie sztangi łamanej ławce ujemnej',
      Reverse_Grip_Bench_French_E_Z_Bar_Press:'Wyciskanie francuskie sztangi łamanej podchwytem leżąc',
      Incline_Two_Arm_French_Dumbbell_Press:'Wyciskanie francuskie hantlii na ławce dodatniej',
      One_Arm_Seated_Dumbbell_Press:'Wyciskanie francuskie hantli jednorącz siedząc',
      Two_Arm_Seated_Dumbbell_Press:'Wyciskanie francuskie hantli oburącz siedząc',
      Close_Grip_Incline_Smith_Machine_Bench_Press:'Wyciskanie na suwnicy smitha na ławce dodatniej wąski rozstaw rąk',
      Close_Grip_Decline_Smith_Machine_Bench_Press:'Wyciskanie na suwnicy smitha na ławce ujemnej wąski rostaw rąk',
      Close_Grip_Smith_Machine_Bench_Press:'Wyciskanie na suwnicy smitha wąski rostaw rąk',
      Close_Grip_Incline_Barbell_Bench_Press:'Wyciskanie sztangi na ławce dodatniej wąski rostaw rąk',
      Close_Grip_Barbell_Bench_Press:'Wyciskanie sztangi na ławce poziomej wąski rostaw rąk',
      Close_Grip_Decline_Barbell_Bench_Press:'Wyciskanie sztangi na ławce ujemnej wąski rostaw rąk', // problem
      Tate_Press_Dumbbell_Press:'Wyciskanie hantlii tate press leżąc'
      // }
    },
    functional_exercises_names:{
      Burpee:'Burpee',
      MountineClimber:'„Wspinaczka”',
      MartwyCiagNaProstychNogach:'Martwy ciąg na prostych nogach',
      Pompki:'Pompki',
      Przysiady:'Przysiady',
      PompkinaPilce:'Pompki na piłce',
      PompkinaBosu:'Pompki na bosu',
      PompkinaKolanach:'Pompki na kolanach',
      Stiff_Legged_Deadlifts:'Martwy ciąg na prostych nogach',
      SkipBokserski:'Skip bokserski',
      Pajacyki:'Pajacyki',
      SwingZkettlebell:'Swing z kettlebell',
      HipThrust:'Wyciskanie sztangi biodrami leżąc na ławce',
      Wykroki:'Wykroki',
      Lunges_with_Dumbbells:'Wykroki z hantlami',
      Lunges_with_Barbell:'Wykroki ze sztangą',
      WykrokiBulgarskie:'Wykroki bułgarskie',
      Skakanka:'Skakanka',
      WykrokizHantlami:'Wykroki z Hantlami',
      WykrokizSztanga:'Wykroki ze sztangą',
      Plank:'Deska',
      PodporBokiem:'Podpór Bokiem',
      PodporTylem:'Podpór Tyłem',
      ElbowPlankKnee:'Elbow plank knee',
      ElbowPlank:'Elbow plank',
      BasicPlank:'Basic plank',
      ExtendedPlank:'Extended plank',
      PlankLegRaise:'Plank leg raise',
      PlankArmReach:'Plank arm reach',
      BallPlank:'Deska ze stopami na piłce gimnastycznej',
      OverheadPress:'Wyciskanie żołnierskie',
      Squats:'Przysiady',
      PrzysiadyzPilkaLekarska:'Przysiady z piłką lekarską',
      KlękaniezPilka:'Klękanie z piłką',
      WchodzeniePoSchodach:'Wchodzenie po schodach',
      UnoszeniePilkiPoPrzekatnej:'Unoszenie piłki po przekątnej',
      Nozyce:'Nożyce',
      PrzysiadyNaJednejNodze:'Przysiady na jednej nodze',
      TRXprzysiadNaJednejNodze:'TRX przysiad na jednej nodze',
      TRXwyciskanie:'TRX wyciskanie',
      TRXwioslowanieTRXwyciaganieRakNadGlowe:'TRX wiosłowanie TRX wyciąganie rąk nad głowę',
      TRXwyciaganieRakNadGlowe:'TRX wyciąganie rąk nad głowę',
      TRXpodciaganieKolanPodKlatkePiersiowa:'TRX podciąganie kolan pod klatkę piersiową',
      TRXdeska:'TRX deska',
      TRXunoszenieBioderDoGory:'TRX unoszenie bioder do góry',
    }
  }
};

export default I18n;
